spring:
  profiles:
    active:
      - dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_devmngsys?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  messages:
    # 配置国际化资源文件的基本名称（配置文件的路径、基本名称）
    basename: i18n.login, i18n.common, i18n.dashboard, i18n.device, i18n.user, i18n.borrow, i18n.return, i18n.backup, i18n.about

---

spring:
  profiles: dev

  thymeleaf:
    cache: false # 禁用thymeleaf缓存

server:
  port: 80

---

spring:
  profiles: prod

server:
  port: 8088